# Generated by Django 4.2.24 on 2025-09-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='gestion.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='gestion.destination'),
        ),
    ]
