# Generated by Django 4.2.24 on 2025-09-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_airlines_trips_departuretime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='price',
        ),
        migrations.AddField(
            model_name='departuretime',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
