# Generated by Django 4.2.24 on 2025-09-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_trips_price_departuretime_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departuretime',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
