# Generated by Django 4.2.24 on 2025-09-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_departuretime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departuretime',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
