# Generated by Django 4.2.24 on 2025-09-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_departuretime_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightrequest',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flightrequest',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='flightrequest',
            name='departure_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests', to='gestion.departuretime'),
        ),
        migrations.AlterField(
            model_name='departuretime',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
