# Generated by Django 4.2.24 on 2025-09-28 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0011_remove_flightrequest_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departuretime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure_times', to=settings.AUTH_USER_MODEL),
        ),
    ]
