# Generated by Django 4.2.24 on 2025-09-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_departuretime_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightrequest',
            name='passengers',
        ),
        migrations.AddField(
            model_name='departuretime',
            name='passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
