# Generated by Django 4.2.24 on 2025-09-28 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0013_remove_flightrequest_passengers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departuretime',
            old_name='passengers',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='duration',
            new_name='passengers',
        ),
        migrations.AddField(
            model_name='trips',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trips',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
