# Generated by Django 4.2.24 on 2025-09-28 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0014_rename_passengers_departuretime_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightrequest',
            name='trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests', to='gestion.trips'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='departure_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_requests_depure_time', to='gestion.departuretime'),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_requests_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
