# Generated by Django 4.2.24 on 2025-09-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_flightrequest_trips_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightrequest',
            old_name='trips',
            new_name='trip',
        ),
    ]
